Add Help command class and sequence diagrams
AY2324S2-CS2103T-W10-1/tp pull request #284
Opened 2024-04-08 13:24 UTC by appleraincoat

Add Help Command class and sequence diagrams.

Abit unsure, please lmk if anything is wrong 😢

2024-04-08 16:43 UTC, UdhayaShan1 requested changes
I think class diagram ok, but sequence diagram seems incomplete, after HelpCommand is returned `RealodexParser` should call execute on it which then creates the CommandResult and returns it to HelpCommand

2024-04-10 08:19 UTC, UdhayaShan1 approved these changes
LGTM, all rise

2024-04-11 06:25 UTC, 4llysa approved these changes
Can add the sequence diagram before merging, or can merge first and we arrange on Friday when we meet

2024-04-11 06:25 UTC, 4llysa commented on docs/DeveloperGuide.md
> +<puml src="diagrams/help/HelpCommand.puml" width="1000" />
Thanks for adding the architecture for help.

2024-04-11 06:25 UTC, 4llysa commented on docs/diagrams/help/HelpSequenceDiagram.puml
> +!include style.puml
Perhaps this diagram should be included in the DG as well, as right now it is not used.

2024-04-11 08:02 UTC, merged